### ISSUE TITLE
拆包的过程是如何调试的

### ISSUE THREAD

**Issue by wangqianjun** [desmond1121/react-native-split#2]
hi, Desmond! 
如题，拆包的过程是怎么做调试的，我想深入了解下打包的过程，能不能debug？

**Comment by desmond1121** [comment]
@wangqianjun 可以，因为是node程序，用WebStorm可以很方便地调试。运行的程序就按 run-example.sh 中的指令即可

**Comment by wangqianjun** [comment]
@desmond1121 我在Webstorm的Terminal中执行run-example.sh中的命令，使用断点，怎么没有作用啊？

**Comment by desmond1121** [comment]
@wangqianjun 使用terminal运行相当于没在WebStorm里运行，断点没用啊，你需要使用相当于Android Studio的run功能启动程序，如下图处：
![image](https://cloud.githubusercontent.com/assets/11497762/26667744/454c432c-46d9-11e7-9155-d1ee29d43d5a.png)
可以自行查找一下方法
