### ISSUE TITLE
为什么SampleA.js里面这样引用模块？

### ISSUE THREAD

**Issue by wangqianjun** [desmond1121/react-native-split#3]
hi，我看到demo里面SampleA.js里面有下面这样一段代码
`import {
  FuncA, FuncB
} from 'example/src/modules';`
我不是很明白为什么可以这样引用，我的理解是import某个模块时可以有两种方式：
1、npm管理的模块可以像上面这样写
2、使用相对路径/绝对路劲，
可是我没看到这边有example文件夹啊。

**Comment by desmond1121** [comment]
@wangqianjun 这是另一种绝对路径的引用，使用package.json中的name作为路径第一个元素即可作为项目路径引用模块，在本项目中就是  example
