### ISSUE TITLE
run-example.sh bug

### ISSUE THREAD

**Issue by 52myu** [desmond1121/react-native-split#5]
个人测试了下 应该这样写android才不会闪退
#!/bin/bash
rm -rf build
mkdir build
node ../index.js --platform android --output build --config .splitconfig --dev false
cur_path=${PWD}
cd android/app/src/main/
rm -rf assets
mkdir assets
cd assets
rm -rf bundle
mkdir bundle
cd ${cur_path}

cp -R build/bundle-output/split/* android/app/src/main/assets/bundle
cd android
./gradlew :app:installDebug
adb shell am start -n com.example/.MainActivity

**Comment by desmond1121** [comment]
@52myu 闪退的堆栈是什么？测试的平台是Windows还是*nix系统？因为我看你这个新脚本的作用 貌似和我原有脚本没有区别

**Comment by 52myu** [comment]
assert目录创建不了，你可以吧  android/app/src/main/   下assets目录删了试一下，测试平台是 mac

**Comment by desmond1121** [comment]
@52myu 已修复，谢谢
